### PR TITLE
redesign header.tsx and add dropdown for the user

### PR DESCRIPTION
**Pull request by chengkangzai**

### CODE REVIEW

**Comment by nubpro** [comment]
The login button is gone after logging out while the dropdown icon remains

**Review by nubpro — CHANGES_REQUESTED** [review]
The login button is gone after logging out while the dropdown icon remains

**Comment by chengkangzai** [comment]
> The login button is gone after logging out while the dropdown icon remains

Fix in https://github.com/nubpro/nakvaksin/pull/28/commits/feeed3a488e87421ba7f78df6dc649a32194417c

**Comment by chengkangzai** [comment]
Solve merge conflict in https://github.com/nubpro/nakvaksin/pull/28/commits/1a1f1fc9e079596de13add4f93f34d938ca1f195

**Comment by nubpro** [comment]
With this round of substantial changes to the header, I have broke the landing page...
It looks broken on mobile view...

can you repair this :) hahaa

**Comment by chengkangzai** [comment]
> With this round of substantial changes to the header, I have broke the landing page...
> It looks broken on mobile view...
> 
> can you repair this :) hahaa

Congrats  ?😂

**Comment by chengkangzai** [comment]
@nubpro  take a look

**Comment by nubpro** [comment]
image

Sorry I should been more clear, the header needs some additional spacing below for mobile view

**Comment by chengkangzai** [comment]
you mean this ? 
image

**Review by nubpro — APPROVED** [review]

**Pull request merged**
