### PR TITLE
Added formatting for phone number logins

### PR DESCRIPTION
**Pull request by bhsz**
Hey there, I just want to say thank you so much for putting this up. I can personally relate to the anxiety of having to check the MySejahtera app every day for my appointment, this would really be of great help to the people.

On MySejahtera, my phone number ID was formatted with a '+' in the beginning. I used that to login but it didn't work, so I thought that I may have forgotten my password. I went ahead and reset my password, but it still didn't work. I then tried "01..." and "601..." which eventually succeeded.

I've added a simple Regex match for phone numbers and formatting in the login function of `auth.ts` to resolve this.

PS This is my first ever open source pull request, hopefully I haven't done anything too wrong. Any advice would be greatly appreciated!

### CODE REVIEW

**Comment by chengkangzai** [comment]
Thank you for bringing this problem up! I'm not too far from you as I'm a second-year student just like you!

We actually have a build it functions in https://github.com/nubpro/nakvaksin/blob/e01ff2dfed2d063a977276dca8db7e8d0d6c2b5c/utils/sanitizePhoneNumber.ts#L15-L17

Would you mind using that function instead? 
https://github.com/nubpro/nakvaksin/blob/e01ff2dfed2d063a977276dca8db7e8d0d6c2b5c/services/auth.ts#L11-L20

Maybe use it like so will be cleaner code.
```
            username: sanitizePhoneNumber(username),
```

**Review by chengkangzai — APPROVED** [review]
Thank you! 

Hope you get your vaccine appointment sooner 😁

**Comment by bhsz** [comment]
Ah I see! Thanks for that, I've changed it. My contribution is now only 1 line! :laughing:

**Comment by chengkangzai** [comment]
> Ah I see! Thanks for that, I've changed it. My contribution is now only 1 line! 😆

My first OSS contribution is also one line xD, isn't It how it should start after all? xD

**Comment by nubpro** [comment]
Whoops, looks like I missed this out...

Thanks for the contribution!

**Pull request merged**
