### PR TITLE
Small improvement for malay translation

### PR DESCRIPTION
**Pull request by qhkm**
Small improvement for malay translation

### CODE REVIEW

**Comment by chengkangzai** [comment]
Thank You ! Apparently my Malay need more improvement   🤣

**Comment by qhkm** [comment]
Haha no worries. great work btw!

**Comment by chengkangzai** [comment]
I will merge your PR after we fix the production error 🙈

**Review by chengkangzai — APPROVED** [review]

**Comment by chengkangzai** [comment]
@qhkm  can you help me to fetch upstream in https://github.com/qhkm/nakvaksin/tree/enhancement/improve-malay-translation ? xD

**Comment by qhkm** [comment]
@chengkangzai sure! done :)

**Comment by chengkangzai** [comment]
@qhkm Thank you very much !

**Pull request merged**
