### PR TITLE
SEO

### PR DESCRIPTION
**Pull request by chengkangzai**
add SEO functionality... Yup, thats it

### CODE REVIEW

**Comment by nubpro** [comment]
Looks like there's conflict on this branch, perhaps disregard all the changes on `pages/index.tsx`.
Since we have a proper domain setup and twitter handler, lets get these pieces updated before we improve our SEO!

**Comment by chengkangzai** [comment]
Let's see if I can resolve locally , if can't then will do.

Will do on morning. G9 xD

**Comment by nubpro** [comment]
U got add the SEO tag into _app?

**Comment by chengkangzai** [comment]
> U got add the SEO tag into _app?

dang forgotten, i am thinking to put it in index.tsx, replace the title tag. ok for that ?

**Review by nubpro — APPROVED** [review]

**Pull request merged**
