### PR TITLE
use "- instead of "N/A"

### PR DESCRIPTION
**Pull request by chengkangzai**

### CODE REVIEW

**Review by nubpro — CHANGES_REQUESTED** [review]
Can you show "Loading" while useQuery is fetching the api?

You can do this by using isLoading returned from useQuery (or in this case, its useVaxSubscription).

**Comment by chengkangzai** [comment]
> Can you show "Loading" while useQuery is fetching the api?
> 
> You can do this by using isLoading returned from useQuery (or in this case, its useVaxSubscription).

added in https://github.com/nubpro/nakvaksin/pull/33/commits/27aeba00800fd003e619ebcee922d2bcdff063ce . 
Verify for me please haha

**Review by nubpro — APPROVED** [review]
I'm good with my changes la....

Can u verify my changes before merging?

**Comment by chengkangzai** [comment]
> I'm good with my changes la....
> 
> Can u verify my changes before merging?

checked as you pushed the commit, looks good

I will proceed to merge

**Pull request merged**
