### PR TITLE
Drop the phone picture underneath 

### PR DESCRIPTION
**Pull request by chengkangzai**

### CODE REVIEW

**Comment by chengkangzai** [comment]
Fix https://github.com/nubpro/nakvaksin/issues/2

**Review by nubpro — CHANGES_REQUESTED** [review]
I see that you are checking user session now, which is awesome 🤞

For that, can we try to reuse the same button but just with a different link instead in <Link> component?

**Comment by chengkangzai** [comment]
I just change the button to component based

**Comment by nubpro** [comment]
@chengkangzai 
Lets disable the curve on mobile screens and give some spacing to the subscription button.

Once thats done, this PR will be shipped :)

**Comment by nubpro** [comment]
To the moon 🚀

**Pull request merged**
