### PR TITLE
Vax status

### PR DESCRIPTION
**Pull request by chengkangzai**

### CODE REVIEW

**Comment by nubpro** [comment]
haha I was worried for a sec that I'm you...

image

**Comment by chengkangzai** [comment]
imposter syndrome? haha 
let me fix it real quick

**Comment by nubpro** [comment]
I've refactored quite a bit for the vax status part.
Less is more, if you find yourself doing a lot of complicated stuff, most likely somewhere some part is off

Need your help on this part:
```
Appointment Date & Time
22-Jun
```

Can you make it so that it displays like this?
`Wednesday, 22 Jun 2021, 8:00 AM`

Probably date-fns or Luxon, I prefer Luxon because of its better timezone localisation

**Review by nubpro — APPROVED** [review]
Looking good, more work to tbd on my side for the subscription form.

I anticipate some small refactoring around Vax Subscription once my branch is merged in.

**Comment by nubpro** [comment]
You try and login with your acc, see got any problem. Otherwise can merge jor

**Comment by chengkangzai** [comment]
ok boss

**Comment by chengkangzai** [comment]
You dont want to add AM/PM anymore ?

**Comment by nubpro** [comment]
> You dont want to add AM/PM anymore ?

I will just use whatever MySejahtera is returning, I dont want to simply assume stuff in case we accidentally made some mistake

**Comment by chengkangzai** [comment]
ok then i will do the honor of merge it and check on production in my side

**Pull request merged**
